#!/usr/bin/env python3
"""
CodeVault Cloud Build Runner
Standalone script to execute optimized Nuitka builds in CI/CD environments.
"""

import os
import sys
import logging
import multiprocessing
import subprocess
import argparse
import json
import re
from pathlib import Path

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - [CloudRunner] - %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# =============================================================================
# Embedded Templates
# =============================================================================

PYTHON_WRAPPER_TEMPLATE = r'''# ============ CODEVAULT LICENSE PROTECTION ============
# This code protects your application with license validation
# Generated by CodeVault (codevault.app)
# Features: Ed25519 signature verification, Binary hash checking, Heartbeat

import sys as _cv_sys
import os as _cv_os
import hashlib as _cv_hashlib
import platform as _cv_platform
import json as _cv_json
import time as _cv_time
from urllib.request import Request as _cv_Request, urlopen as _cv_urlopen
from urllib.error import URLError as _cv_URLError
import base64 as _cv_base64
import threading as _cv_threading
import atexit as _cv_atexit

# Configuration
_CV_LICENSE_KEY = "{license_key}"
_CV_SERVER_URL = "{server_url}"
_CV_PUBLIC_KEY = """{public_key}"""
_CV_BINARY_HASH = "{binary_hash}"
_CV_HEARTBEAT_INTERVAL = {heartbeat_interval}
_CV_APP_NAME = "{app_name}"
_CV_LEASE_ENABLED = {lease_enabled}
_CV_SHOW_BRANDING = {show_branding}

# Lease configuration
_CV_LEASE_DURATION = 24 * 60 * 60  # 24 hours
_CV_CLOCK_DRIFT_MAX = 60 * 60  # 1 hour max drift
_CV_SESSION_TOKEN = None
_CV_HEARTBEAT_THREAD = None
_CV_HEARTBEAT_STOP = _cv_threading.Event()

# =============================================================================
# ERROR DISPLAY - GUI and console fallback
# =============================================================================

def _cv_show_error(title, message, details=None):
    """Show error with GUI and console fallback."""
    # Try GUI first
    try:
        import tkinter as tk
        from tkinter import messagebox
        root = tk.Tk()
        root.withdraw()
        root.attributes('-topmost', True)
        full_message = message
        if details:
            full_message += f"\n\nDetails: {details}"
        full_message += "\n\nTroubleshooting:\n- Check license key\n- Verify internet connection\n- Contact support"
        messagebox.showerror(title, full_message)
        root.destroy()
    except:
        pass
    
    # Console fallback
    print("\n" + "=" * 60)
    print(f"  [ERROR] {title}")
    print("=" * 60)
    print(f"\n{message}")
    if details:
        print(f"\nDetails: {details}")
    print("=" * 60)
    try:
        input("\nPress Enter to exit...")
    except:
        pass
    _cv_sys.exit(1)

# =============================================================================
# BINARY INTEGRITY - Verify executable hasn't been tampered with
# =============================================================================

def _cv_verify_binary_integrity():
    """Verify the binary matches the expected hash."""
    if not _CV_BINARY_HASH or _CV_BINARY_HASH == "skip":
        return True
    
    try:
        exe_path = _cv_sys.executable if getattr(_cv_sys, 'frozen', False) else _cv_os.path.abspath(__file__)
        hash_obj = _cv_hashlib.sha256()
        with open(exe_path, 'rb') as f:
            while chunk := f.read(8192):
                hash_obj.update(chunk)
        actual_hash = hash_obj.hexdigest()
        if actual_hash != _CV_BINARY_HASH:
            _cv_show_error("BINARY TAMPERED", 
                          "The executable has been modified.",
                          "This may indicate tampering or corruption.")
            return False
        return True
    except Exception as e:
        print(f"[CodeVault] Warning: Could not verify binary integrity: {e}")
        return True  # Allow on error

# =============================================================================
# ED25519 SIGNATURE VERIFICATION
# =============================================================================

def _cv_verify_signature(message: bytes, signature_b64: str) -> bool:
    """Verify Ed25519 signature."""
    if not _CV_PUBLIC_KEY or _CV_PUBLIC_KEY == "skip":
        print("[CodeVault] Security error: no public key configured")
        return False
    
    try:
        from cryptography.hazmat.primitives.serialization import load_pem_public_key
        from cryptography.exceptions import InvalidSignature
        
        # Load PEM public key
        public_key = load_pem_public_key(_CV_PUBLIC_KEY.encode())
        
        # Decode signature
        signature = _cv_base64.b64decode(signature_b64)
        
        # Verify
        try:
            public_key.verify(signature, message)
            return True
        except InvalidSignature:
            return False
    except ImportError:
        print("[CodeVault] Security error: cryptography is required for signature verification")
        return False
    except Exception as e:
        print(f"[CodeVault] Security error: signature verification failed: {e}")
        return False

def _cv_build_signature_message(result: dict) -> bytes:
    """Build canonical signature message (must match server-side signing)."""
    features_json = _cv_json.dumps(sorted(result.get("features", [])), sort_keys=True)
    variables_json = _cv_json.dumps(result.get("variables", {}), sort_keys=True)
    msg = "|".join(str(v) for v in [
        result.get("status", ""),
        result.get("expires_at", "") or "",
        features_json,
        variables_json,
        result.get("client_nonce", ""),
        result.get("server_nonce", ""),
        result.get("timestamp", ""),
        result.get("server_time", ""),
    ])
    return msg.encode()

# =============================================================================
# HEARTBEAT - Floating license support
# =============================================================================

def _cv_heartbeat_worker():
    """Background thread for sending periodic heartbeats."""
    while not _CV_HEARTBEAT_STOP.is_set():
        _CV_HEARTBEAT_STOP.wait(_CV_HEARTBEAT_INTERVAL)
        if _CV_HEARTBEAT_STOP.is_set():
            break
        _cv_send_heartbeat()

def _cv_send_heartbeat():
    """Send heartbeat to server."""
    global _CV_SESSION_TOKEN
    if not _CV_SESSION_TOKEN:
        return
    
    try:
        data = _cv_json.dumps({
            "license_key": _CV_LICENSE_KEY,
            "session_token": _CV_SESSION_TOKEN,
            "action": "heartbeat"
        }).encode()
        req = _cv_Request(f"{_CV_SERVER_URL}/api/v1/license/heartbeat", 
                         data=data, headers={"Content-Type": "application/json"})
        with _cv_urlopen(req, timeout=10) as resp:
            result = _cv_json.loads(resp.read().decode())
            if result.get("status") != "valid":
                print("[CodeVault] Heartbeat failed - session may be expired")
    except Exception as e:
        print(f"[CodeVault] Heartbeat error: {e}")

def _cv_start_heartbeat():
    """Start heartbeat thread."""
    global _CV_HEARTBEAT_THREAD
    if _CV_HEARTBEAT_INTERVAL > 0 and not _CV_HEARTBEAT_THREAD:
        _CV_HEARTBEAT_THREAD = _cv_threading.Thread(target=_cv_heartbeat_worker, daemon=True)
        _CV_HEARTBEAT_THREAD.start()
        _cv_atexit.register(_cv_stop_heartbeat)

def _cv_stop_heartbeat():
    """Stop heartbeat thread."""
    _CV_HEARTBEAT_STOP.set()
    if _CV_HEARTBEAT_THREAD:
        _CV_HEARTBEAT_THREAD.join(timeout=5)

def _cv_get_hwid():
    """Generate hardware ID with MAC address for better uniqueness."""
    try:
        import uuid as _cv_uuid
        # Try to get MAC address
        mac = _cv_uuid.getnode()
        mac_str = ':'.join(['{:02x}'.format((mac >> elements) & 0xff) for elements in range(0, 8*6, 8)][::-1])
        info = f"{_cv_platform.node()}|{_cv_platform.system()}|{_cv_platform.machine()}|{_cv_platform.processor()}|{mac_str}"
        return _cv_hashlib.sha256(info.encode()).hexdigest()
    except Exception:
        try:
            info = f"{_cv_platform.node()}|{_cv_platform.system()}|{_cv_platform.machine()}|{_cv_platform.processor()}"
            return _cv_hashlib.sha256(info.encode()).hexdigest()
        except:
            return "unknown-hwid"

def _cv_get_license_key_path():
    """Get path to license.key file next to the executable."""
    try:
        if getattr(_cv_sys, 'frozen', False):
            # Running as compiled exe (Nuitka/PyInstaller)
            exe_dir = _cv_os.path.dirname(_cv_sys.executable)
        else:
            # Running as script
            exe_dir = _cv_os.path.dirname(_cv_os.path.abspath(__file__))
        
        # Try executable directory first
        key_path = _cv_os.path.join(exe_dir, "license.key")
        
        # Test if we can write to this location
        try:
            test_file = _cv_os.path.join(exe_dir, ".cv_write_test")
            with open(test_file, 'w') as f:
                f.write("test")
            _cv_os.remove(test_file)
            print(f"[CodeVault] License will be saved to: {key_path}")
            return key_path
        except Exception as write_err:
            # Fall back to user's home directory if exe dir is not writable
            print(f"[CodeVault] Cannot write to exe directory: {exe_dir}")
            print(f"[CodeVault] Reason: {write_err}")
            home_dir = _cv_os.path.expanduser("~")
            app_data_dir = _cv_os.path.join(home_dir, ".codevault")
            try:
                _cv_os.makedirs(app_data_dir, exist_ok=True)
            except Exception:
                pass
            fallback_path = _cv_os.path.join(app_data_dir, "license.key")
            print(f"[CodeVault] Using fallback path: {fallback_path}")
            return fallback_path
            
    except Exception as e:
        # Final fallback
        print(f"[CodeVault] Error determining license path: {e}")
        home_dir = _cv_os.path.expanduser("~")
        return _cv_os.path.join(home_dir, "license.key")

def _cv_get_lease_path():
    """Get path to license.lease file next to the executable."""
    try:
        # Use same directory as license.key file for consistency
        key_path = _cv_get_license_key_path()
        lease_dir = _cv_os.path.dirname(key_path)
        lease_path = _cv_os.path.join(lease_dir, "license.lease")
        return lease_path
            
    except Exception as e:
        # Final fallback
        print(f"[CodeVault] Error determining lease path: {e}")
        home_dir = _cv_os.path.expanduser("~")
        return _cv_os.path.join(home_dir, "license.lease")

def _cv_get_machine_secret():
    """Generate a machine-specific secret for encryption."""
    try:
        info = f"{_cv_platform.node()}|{_cv_platform.machine()}|{_cv_platform.processor()}|CV_SALT_2026"
        return _cv_hashlib.sha256(info.encode()).digest()
    except Exception:
        return _cv_hashlib.sha256(b"fallback_secret").digest()

def _cv_xor_encrypt(data, key):
    """XOR encryption (fallback only)."""
    result = bytearray()
    key_bytes = key if isinstance(key, bytes) else key.encode()
    for i, b in enumerate(data):
        result.append(b ^ key_bytes[i % len(key_bytes)])
    return bytes(result)

def _cv_encrypt_lease(lease_data):
    """Encrypt lease with AES-256-GCM (or XOR fallback)."""
    try:
        secret = _cv_get_machine_secret()
        data_json = _cv_json.dumps(lease_data).encode('utf-8')

        # Try AES-256-GCM first (secure)
        try:
            from cryptography.hazmat.primitives.ciphers.aead import AESGCM
            import secrets as _secrets
            nonce = _secrets.token_bytes(12)
            aesgcm = AESGCM(secret)
            ciphertext = aesgcm.encrypt(nonce, data_json, None)
            return _cv_base64.b64encode(b"AES:" + nonce + ciphertext).decode()
        except ImportError:
            # Fallback to XOR if cryptography not available
            encrypted = _cv_xor_encrypt(data_json, secret)
            return _cv_base64.b64encode(b"XOR:" + encrypted).decode()
    except Exception:
        return None

def _cv_decrypt_lease(encrypted_data):
    """Decrypt lease (supports both AES and XOR)."""
    try:
        secret = _cv_get_machine_secret()
        raw = _cv_base64.b64decode(encrypted_data)

        # Check encryption method
        if raw.startswith(b"AES:"):
            try:
                from cryptography.hazmat.primitives.ciphers.aead import AESGCM
                nonce = raw[4:16]
                ciphertext = raw[16:]
                aesgcm = AESGCM(secret)
                data_json = aesgcm.decrypt(nonce, ciphertext, None)
                return _cv_json.loads(data_json.decode('utf-8'))
            except Exception:
                return None
        elif raw.startswith(b"XOR:"):
            encrypted = raw[4:]
            data_json = _cv_xor_encrypt(encrypted, secret)
            return _cv_json.loads(data_json.decode('utf-8'))
        else:
            return None
    except Exception:
        return None

def _cv_create_lease(license_key, hwid, server_time, duration=_CV_LEASE_DURATION):
    """Create a new lease token."""
    return {
        "license_key_hash": _cv_hashlib.sha256(license_key.encode()).hexdigest(),
        "hwid": hwid,
        "expires_at": server_time + duration,
        "server_time": server_time,
        "validated_at": int(_cv_time.time())
    }

def _cv_save_lease(lease_data):
    """Save encrypted lease to file using atomic write."""
    if not _CV_LEASE_ENABLED:
        return False
    try:
        lease_path = _cv_get_lease_path()
        encrypted = _cv_encrypt_lease(lease_data)
        if encrypted:
            # Atomic write: temp file + rename to prevent corruption
            import tempfile
            lease_dir = _cv_os.path.dirname(lease_path)
            fd, temp_path = tempfile.mkstemp(dir=lease_dir, prefix='.tmp_', text=True)
            try:
                with _cv_os.fdopen(fd, 'w', encoding='utf-8') as f:
                    f.write(encrypted)
                _cv_os.replace(temp_path, lease_path)
            except:
                try:
                    _cv_os.unlink(temp_path)
                except:
                    pass
                raise
            print("[CodeVault] Lease saved (24h offline access)")
            return True
    except Exception:
        pass
    return False

def _cv_load_lease():
    """Load and decrypt lease from file."""
    if not _CV_LEASE_ENABLED:
        return None
    try:
        lease_path = _cv_get_lease_path()
        if _cv_os.path.exists(lease_path):
            with open(lease_path, 'r', encoding='utf-8') as f:
                return _cv_decrypt_lease(f.read().strip())
    except Exception:
        pass
    return None

def _cv_validate_lease(license_key, hwid):
    """Validate an existing lease."""
    lease = _cv_load_lease()
    if not lease:
        return False, "No lease found"

    if lease.get("hwid") != hwid:
        return False, "HWID mismatch"

    key_hash = _cv_hashlib.sha256(license_key.encode()).hexdigest()
    if lease.get("license_key_hash") != key_hash:
        return False, "License mismatch"

    if int(_cv_time.time()) > lease.get("expires_at", 0):
        return False, "Lease expired"

    remaining = lease.get("expires_at", 0) - int(_cv_time.time())
    hours = remaining // 3600
    mins = (remaining % 3600) // 60
    print(f"[CodeVault] Offline lease valid ({hours}h {mins}m remaining)")
    return True, "Valid"

def _cv_validate_license(key, hwid, api_url):
    """Validate license key with the server. Returns (success, server_time, session_token)"""
    print(f"[CodeVault] Validating license with server...")
    timestamp = int(_cv_time.time())
    try:
        import secrets as _secrets
        nonce = _secrets.token_hex(16)
    except ImportError:
        import random
        nonce = ''.join(random.choices('0123456789abcdef', k=32))

    data = _cv_json.dumps({
        "license_key": key,
        "hwid": hwid,
        "machine_name": _cv_platform.node(),
        "timestamp": timestamp,
        "nonce": nonce
    }).encode()

    req = _cv_Request(api_url, data=data, headers={"Content-Type": "application/json"})
    try:
        with _cv_urlopen(req, timeout=15) as resp:
            body = resp.read().decode()
            result = _cv_json.loads(body)
            server_time = result.get("server_time", result.get("timestamp", timestamp))
            
            signature = result.get("signature")
            if not signature:
                print("[CodeVault] Security error: server response missing signature")
                return False, 0, None
            if not _cv_verify_signature(_cv_build_signature_message(result), signature):
                print("[CodeVault] Security error: invalid server signature")
                return False, 0, None
            
            session_token = result.get("session_token")
            is_valid = result.get("status") == "valid"
            return is_valid, server_time, session_token
    except _cv_URLError as e:
        reason = getattr(e, 'reason', str(e))
        print(f"[CodeVault] Connection error: {reason}")
        return None, 0, None  # None = connection error (allows offline fallback)
    except Exception as e:
        print(f"[CodeVault] Validation error: {type(e).__name__}: {e}")
        return False, 0, None

def _cv_prompt_license():
    """Prompt user for license key using console."""
    print("=" * 50)
    print("  License Required")
    print("=" * 50)
    try:
        return input("Enter license key: ").strip()
    except Exception:
        return None

def _cv_license_check():
    """Main license validation with offline lease support, Ed25519 signatures, and heartbeat."""
    global _CV_SESSION_TOKEN
    
    LICENSE_KEY = "{license_key}"
    API_URL = "{server_url}"

    # DEMO mode - skip validation
    if LICENSE_KEY == "DEMO":
        print("[CodeVault] Running in DEMO mode")
        return True

    # Verify binary integrity first
    if not _cv_verify_binary_integrity():
        return False

    hwid = _cv_get_hwid()
    key_file = _cv_get_license_key_path()

    # Check if we need to prompt for license (generic build)
    if LICENSE_KEY in ("GENERIC_BUILD", "generic", "", None):
        # Try saved key first
        saved_key = None
        if _cv_os.path.exists(key_file):
            try:
                with open(key_file, "r", encoding="utf-8") as f:
                    saved_key = f.read().strip()
            except Exception:
                pass

        if saved_key:
            print(f"[CodeVault] Found saved license, validating...")
            success, server_time, session_token = _cv_validate_license(saved_key, hwid, API_URL)

            if success is True:
                # Store session token for heartbeat
                if session_token:
                    _CV_SESSION_TOKEN = session_token
                    _cv_start_heartbeat()
                
                # Online validation succeeded - create/update lease
                local_time = int(_cv_time.time())
                drift = abs(local_time - server_time)
                if drift <= _CV_CLOCK_DRIFT_MAX:
                    lease = _cv_create_lease(saved_key, hwid, server_time)
                    _cv_save_lease(lease)
                else:
                    print(f"[CodeVault] Clock drift detected ({drift}s), lease not saved")
                print("[CodeVault] License verified!")
                return True
            elif success is None:
                # Connection error - try offline lease
                print("[CodeVault] Server unreachable, checking offline lease...")
                valid, msg = _cv_validate_lease(saved_key, hwid)
                if valid:
                    print("[CodeVault] Running with offline lease")
                    return True
                else:
                    print(f"[CodeVault] Offline lease invalid: {msg}")
            else:
                # License rejected
                print("[CodeVault] Saved license is invalid or expired.")
                try:
                    _cv_os.remove(key_file)
                    lease_path = _cv_get_lease_path()
                    if _cv_os.path.exists(lease_path):
                        _cv_os.remove(lease_path)
                except Exception:
                    pass

        # Prompt for new license
        key = _cv_prompt_license()
        if not key:
            _cv_show_error("NO LICENSE KEY", "No license key was provided.", "Please run the application again and enter a valid license key.")
            return False

        # Validate the entered key
        success, server_time, session_token = _cv_validate_license(key, hwid, API_URL)

        if success is True:
            # Store session token for heartbeat
            if session_token:
                _CV_SESSION_TOKEN = session_token
                _cv_start_heartbeat()
            
            # Save license key to the same directory as the executable (atomic write)
            try:
                key_dir = _cv_os.path.dirname(key_file)
                if key_dir and not _cv_os.path.exists(key_dir):
                    _cv_os.makedirs(key_dir, exist_ok=True)

                # Atomic write to prevent corruption
                import tempfile
                fd, temp_path = tempfile.mkstemp(dir=key_dir, prefix='.tmp_', text=True)
                try:
                    with _cv_os.fdopen(fd, 'w', encoding='utf-8') as f:
                        f.write(key)
                    _cv_os.replace(temp_path, key_file)
                except:
                    try:
                        _cv_os.unlink(temp_path)
                    except:
                        pass
                    raise

                print(f"[CodeVault] License saved to: {key_file}")
            except Exception as e:
                print(f"[CodeVault] Warning: Could not save license: {e}")

            # Create lease for offline use
            local_time = int(_cv_time.time())
            drift = abs(local_time - server_time)
            if drift <= _CV_CLOCK_DRIFT_MAX:
                lease = _cv_create_lease(key, hwid, server_time)
                _cv_save_lease(lease)
            else:
                print(f"[CodeVault] Clock drift detected ({drift}s), lease not saved")

            print("[CodeVault] License activated!")
            return True
        elif success is None:
            _cv_show_error("OFFLINE - LICENSE REQUIRED",
                          "Cannot validate license - server unreachable.",
                          "First-time activation requires an internet connection.")
        else:
            _cv_show_error("INVALID LICENSE", "The license key was rejected.", "Please check your license key and try again.")

    else:
        # Fixed license key mode
        success, server_time, session_token = _cv_validate_license(LICENSE_KEY, hwid, API_URL)

        if success is True:
            # Store session token for heartbeat
            if session_token:
                _CV_SESSION_TOKEN = session_token
                _cv_start_heartbeat()
            
            # Create lease for offline use
            local_time = int(_cv_time.time())
            drift = abs(local_time - server_time)
            if drift <= _CV_CLOCK_DRIFT_MAX:
                lease = _cv_create_lease(LICENSE_KEY, hwid, server_time)
                _cv_save_lease(lease)
            else:
                print(f"[CodeVault] Clock drift detected ({drift}s), lease not saved")
            print("[CodeVault] License verified!")
            return True
        elif success is None:
            # Connection error - try offline lease
            print("[CodeVault] Server unreachable, checking offline lease...")
            valid, msg = _cv_validate_lease(LICENSE_KEY, hwid)
            if valid:
                print("[CodeVault] Running with offline lease")
                return True
            else:
                _cv_show_error("OFFLINE - LICENSE REQUIRED",
                              f"Cannot validate license offline: {msg}",
                              "Please connect to the internet to validate your license.")
        else:
            _cv_show_error("LICENSE INVALID", "The embedded license key was rejected by the server.", None)

    return False

# Run license check on startup
_cv_license_check()
# === End CodeVault License Protection ===
'''

PYTHON_DEMO_WRAPPER = r'''# === CodeVault License Protection (Demo Mode) ===
import time as _cv_time
import sys as _cv_sys

_CV_DEMO_START = _cv_time.time()
_CV_DEMO_DURATION = 60 * 60  # 1 hour demo

print("[CodeVault] Running in DEMO mode (1 hour limit)")

def _cv_check_demo_expired():
    """Check if demo has expired."""
    elapsed = _cv_time.time() - _CV_DEMO_START
    if elapsed > _CV_DEMO_DURATION:
        print("[CodeVault] Demo period has expired!")
        try:
            input("Press Enter to exit...")
        except Exception:
            pass
        _cv_sys.exit(1)

# Check periodically (import this check into your main loop if needed)
_cv_check_demo_expired()
# === End CodeVault License Protection ===
'''

# =============================================================================
# Cloud Runner Logic
# =============================================================================


class CloudRunner:
    """Execute optimized builds with Nuitka and Turbo Mode."""

    def __init__(self, source_dir: Path, output_dir: Path, config: dict):
        self.source_dir = source_dir
        self.output_dir = output_dir
        self.config = config

    def run(self) -> Path:
        """Execute the full build pipeline."""
        logger.info(f"Starting build for: {self.config.get('project_name', 'Unknown')}")

        # 1. Prepare Environment
        self._prepare_dependencies()

        # 2. Find and validate entry file
        entry_file = self._find_entry_file(self.config.get("entry_file", "main.py"))

        # 2.5 Syntax Check
        self._check_syntax(entry_file)

        # 3. Inject Wrapper
        self._inject_license_wrapper(entry_file)

        # 4. Compile
        return self._compile_nuitka(entry_file)

    def _check_syntax(self, entry_file: str):
        """Check Python syntax of the entry file."""
        entry_path = self.source_dir / entry_file
        try:
            with open(entry_path, "r", encoding="utf-8") as f:
                source = f.read()
            compile(source, str(entry_path), "exec")
        except SyntaxError as e:
            error_msg = f"Syntax Error in {entry_file} line {e.lineno}: {e.msg}"
            logger.error(error_msg)

            # Write to error file for the workflow to pick up
            # Write to both output_dir AND source_dir for compatibility
            err_file = self.output_dir / "error_message.txt"
            err_file_src = self.source_dir / "error_message.txt"

            # Ensure output dir exists
            self.output_dir.mkdir(parents=True, exist_ok=True)
            with open(err_file, "w") as f:
                f.write(error_msg)
            # Also write to source dir for cloud build compatibility
            with open(err_file_src, "w") as f:
                f.write(error_msg)

            sys.exit(1)
        except Exception as e:
            logger.warning(f"Could not verify syntax: {e}")

    def _find_entry_file(self, entry_file: str) -> str:
        """Find entry file with smart fallback for various directory structures."""
        # Try exact path first
        if (self.source_dir / entry_file).exists():
            logger.info(f"Found entry file: {entry_file}")
            return entry_file

        # Try flattened structure (e.g., "app/main.py" -> "main.py")
        flat_entry = Path(entry_file).name
        if (self.source_dir / flat_entry).exists():
            logger.warning(
                f"Entry file '{entry_file}' not found, using flattened: '{flat_entry}'"
            )
            return flat_entry

        # Try common Python entry point names
        common_entries = [
            "main.py",
            "app.py",
            "__main__.py",
            "run.py",
            "start.py",
            "index.py",
        ]
        for alt in common_entries:
            if (self.source_dir / alt).exists():
                logger.warning(
                    f"Entry file '{entry_file}' not found, using alternative: '{alt}'"
                )
                return alt

        # List available Python files for better error message
        py_files = list(self.source_dir.glob("*.py"))
        if py_files:
            # Use the first Python file as a last resort
            fallback = py_files[0].name
            logger.warning(
                f"No standard entry file found, using first Python file: '{fallback}'"
            )
            return fallback

        # No Python files at all - this will fail
        all_files = [f.name for f in self.source_dir.iterdir() if f.is_file()][:10]
        raise FileNotFoundError(
            f"Entry file '{entry_file}' not found. No Python files in source root. "
            f"Files found: {all_files}"
        )

    def _prepare_dependencies(self):
        """Install dependencies with smart filtering."""
        req_file = self.source_dir / "requirements.txt"
        if req_file.exists():
            logger.info("Installing dependencies...")

            # Filter requirements
            content = req_file.read_text(encoding="utf-8")
            filtered_lines = []

            for line in content.splitlines():
                line = line.strip()
                if not line or line.startswith("#"):
                    continue

                # Skip heavy C-dependant libs if not supported
                if re.search(r"^(ta-lib|TA-Lib)", line, re.IGNORECASE):
                    logger.warning("Skipping ta-lib (requires system libs)")
                    continue

                filtered_lines.append(line)

            # Write filtered
            filtered_req = self.source_dir / "requirements_filtered.txt"
            filtered_req.write_text("\n".join(filtered_lines), encoding="utf-8")

            subprocess.check_call(
                [
                    sys.executable,
                    "-m",
                    "pip",
                    "install",
                    "-r",
                    str(filtered_req),
                    "--quiet",
                    "--disable-pip-version-check",
                    "--no-warn-script-location",
                ],
                stdout=sys.stdout,
                stderr=sys.stderr,
            )

    def _uses_tkinter(self) -> bool:
        """Check if project uses tkinter by scanning source files."""
        try:
            for py_file in self.source_dir.rglob("*.py"):
                try:
                    content = py_file.read_text(encoding="utf-8", errors="ignore")
                    # Check for tkinter imports
                    if re.search(
                        r"^(?:import\s+tkinter|from\s+tkinter\s+import)",
                        content,
                        re.MULTILINE,
                    ):
                        return True
                except Exception:
                    continue
            return False
        except Exception:
            return False

    def _inject_license_wrapper(self, entry_file: str):
        """Inject license wrapper into entry file with Ed25519, binary hash, and heartbeat."""
        entry_path = self.source_dir / entry_file
        if not entry_path.exists():
            raise FileNotFoundError(f"Entry file not found: {entry_file}")

        original_code = entry_path.read_text(encoding="utf-8")
        license_key = self.config.get("license_key", "GENERIC_BUILD")
        api_url = self.config.get("api_url", "")

        # Security features
        public_key = self.config.get("signing_public_key") or self.config.get(
            "public_key", ""
        )

        # Binary hash verification - only enable if explicitly set (default OFF for AV compatibility)
        enable_binary_hash = self.config.get("enable_binary_hash", False)
        if enable_binary_hash:
            binary_hash = self.config.get("binary_hash", "skip")
            logger.info(
                "Injecting license protection (Ed25519 + Binary Hash + Heartbeat)..."
            )
        else:
            binary_hash = "skip"  # Skip binary hash verification
            logger.info(
                "Injecting license protection (Ed25519 + Heartbeat) - Binary hash disabled for AV compatibility..."
            )

        heartbeat_interval = self.config.get("heartbeat_interval", 300)
        app_name = self.config.get("app_name", "Protected Application")
        lease_enabled = self.config.get("lease_enabled", True)
        show_branding = self.config.get("show_branding", True)

        if license_key == "demo":
            wrapper = PYTHON_DEMO_WRAPPER
        else:
            wrapper = (
                PYTHON_WRAPPER_TEMPLATE.replace("{license_key}", license_key)
                .replace("{server_url}", api_url)
                .replace("{public_key}", public_key)
                .replace("{binary_hash}", binary_hash)
                .replace("{heartbeat_interval}", str(heartbeat_interval))
                .replace("{app_name}", app_name)
                .replace("{lease_enabled}", "True" if lease_enabled else "False")
                .replace("{show_branding}", "True" if show_branding else "False")
            )

        entry_path.write_text(wrapper + "\n\n" + original_code, encoding="utf-8")

    def _compile_nuitka(self, entry_file: str) -> Path:
        """Run Nuitka with Turbo Mode optimizations."""
        output_name = self.config.get("output_name") or "app"

        # CRITICAL FIX: Ensure output_name is never empty
        if not output_name or output_name.strip() == "":
            output_name = "app"
            logger.warning("output_name was empty, defaulting to 'app'")

        # Sanitize output name (remove invalid characters)
        output_name = "".join(c for c in output_name if c.isalnum() or c in "-_")
        if not output_name:
            output_name = "app"

        logger.info(f"Output name: {output_name}")

        # Platform specific output naming
        if sys.platform == "win32":
            output_exe = f"{output_name}.exe"
        elif sys.platform == "darwin":
            output_exe = f"{output_name}.app"
        else:
            output_exe = output_name

        cmd = [
            sys.executable,
            "-m",
            "nuitka",
            "--onefile",  # Single self-contained EXE with all DLLs embedded
            "--standalone",  # Required base for onefile
            "--assume-yes-for-downloads",
            "--lto=no",  # Disable Link-Time Optimization (much faster builds)
        ]

        # Add macOS specific flags
        if sys.platform == "darwin":
            cmd.append("--macos-create-app-bundle")

        # Windows/Wine specific handling
        if sys.platform == "win32":
            logger.info("Windows/Wine: Using --onefile for single EXE output")
            # Use pefile for dependency detection (works better in Wine)
            cmd.append("--experimental=use_pefile_recursion")
            # Add Windows metadata for better legitimacy (reduces AV false positives)
            cmd.extend(
                [
                    "--company-name=CodeVault",
                    f"--product-name={output_name}",
                    "--file-version=1.0.0.0",
                    "--product-version=1.0.0.0",
                    f"--file-description={output_name} - CodeVault Protected Application",
                    "--copyright=Copyright 2025 CodeVault",
                ]
            )
        else:
            logger.info("Using --onefile mode (single self-contained binary)")

        cmd.extend(
            [f"--output-filename={output_exe}", f"--output-dir={self.output_dir}"]
        )

        # Parallel jobs - OPTIMIZED for E2_HIGHCPU_8 (8 vCPUs)
        available_cpus = multiprocessing.cpu_count()
        env_jobs = os.environ.get("NUITKA_JOBS", "")

        if sys.platform == "win32":
            # Windows/Wine is unstable with multiple jobs - keep at 1
            job_count = 1
            logger.warning("Windows/Wine: Using 1 job for stability")
        else:
            # Linux: Use environment variable or calculate optimal jobs
            if env_jobs:
                job_count = int(env_jobs)
                logger.info(f"Using NUITKA_JOBS from environment: {job_count}")
            elif available_cpus >= 8:
                # On 8+ core machines, use 6 jobs (leave 2 for system)
                job_count = 6
                logger.info(f"Using {job_count} parallel jobs (8-core optimization)")
            elif available_cpus >= 4:
                # On 4+ core machines, use 3 jobs
                job_count = 3
                logger.info(f"Using {job_count} parallel jobs (4-core optimization)")
            elif available_cpus >= 2:
                job_count = 2
                logger.info(f"Using {job_count} parallel jobs")
            else:
                job_count = 1
                logger.warning("Single CPU detected, using 1 job")

        cmd.append(f"--jobs={job_count}")
        logger.info(
            f"Using {job_count} CPU cores (detected {available_cpus} available)"
        )

        # Turbo Mode Blacklist
        # Standard blacklist + aggressive optimizations
        blacklist = [
            "test",
            "unittest",
            "pytest",
            "pdb",
            "doctest",
            "trace",
            "pyclbr",
            "pstats",
            "profile",
            "cProfile",
            "imaplib",
            "poplib",
            "smtplib",
            "nntplib",
            "ftplib",
            "telnetlib",
            "cgi",
            "cgitb",
            "wsgiref",
            "http.server",
            "xmlrpc",
            "pydoc",
            "webbrowser",
            "turtle",
            "turtledemo",
            "idlelib",
            "tkinter",
            "curses",
            # Heavy libraries that cause Nuitka recursion issues - compiled as bytecode instead
            "sqlalchemy",
            "pandas",
            "numpy",
            "scipy",
            "PIL",
            "matplotlib",
            "certifi",
            "_uuid",
            "_zoneinfo",
            "_cffi_backend",
            "_lzma",
            "_bz2",
            "_socket",
            "_sqlite3",
            "_asyncio",
            "_overlapped",
            "_queue",
            "_multiprocessing",
            "_decimal",
            "_elementtree",
            "_ctypes",
            "cryptography",
            "cffi",
        ]

        compatibility_mode = self.config.get("compatibility_mode", False)

        if not compatibility_mode:
            logger.info("⚡ TURBO MODE ENABLED")
            # Enable anti-bloat to reduce compilation size and time
            cmd.append("--enable-plugin=anti-bloat")

            # Aggressive exclusions (but keep Unicode support)
            turbo_exclusions = [
                "encodings.cp1006",
                "encodings.cp1026",
                "encodings.cp1125",
                "encodings.cp1140",
                "lzma",
                "bz2",
                "calendar",
                "sched",
            ]
            blacklist.extend(turbo_exclusions)
        else:
            logger.info("Using Compatibility Mode (Standard optimizations)")
            # In compat mode, we might disable anti-bloat if it causes issues,
            # or keep it enabled but less aggressive. For now, let's enable it as standard.
            cmd.append("--enable-plugin=anti-bloat")

        # Ensure UTF-8 and Unicode support for emojis and international characters
        # Include necessary encoding modules for full Unicode support
        cmd.append("--include-module=encodings.utf_8")
        cmd.append("--include-module=encodings.utf_8_sig")
        cmd.append("--include-module=encodings.unicode_escape")
        cmd.append("--include-module=encodings.raw_unicode_escape")

        for module in blacklist:
            cmd.append(f"--nofollow-import-to={module}")

        # NOTE: Removed --enable-plugin=tk-inter as it significantly slows builds
        # The wrapper code has fallback for when tkinter is not available
        # Only add it if the project actually imports tkinter
        if self._uses_tkinter():
            logger.info("Project uses tkinter, enabling tk-inter plugin")
            cmd.append("--enable-plugin=tk-inter")
        else:
            logger.info("Skipping tk-inter plugin (not used by project)")

        # Add entry file
        cmd.append(str(self.source_dir / entry_file))

        logger.info("Starting Nuitka compilation...")
        logger.info(f"Entry file: {entry_file}")
        logger.info(f"Output file: {output_exe}")
        logger.info(f"Output dir: {self.output_dir}")

        # Log the full command for debugging
        logger.info(f"Nuitka command (first 500 chars): {' '.join(cmd)[:500]}...")

        if sys.platform == "win32":
            # Use subprocess with list-based arguments to avoid command injection
            # Pass environment variables directly to the call
            custom_env = os.environ.copy()
            custom_env["WINEDEBUG"] = "-all"

            logger.info(
                f"Nuitka command (Windows/Subprocess): {' '.join(cmd)[:500]}..."
            )
            subprocess.check_call(
                cmd, stdout=sys.stdout, stderr=sys.stderr, env=custom_env
            )
        else:
            subprocess.check_call(cmd, stdout=sys.stdout, stderr=sys.stderr)

        final_path = self.output_dir / output_exe
        if not final_path.exists():
            # Search recursive if Nuitka moved it
            found = list(self.output_dir.rglob(output_exe))
            if found:
                final_path = found[0]
            else:
                # Fallback for macOS: checking if it produced a binary instead of .app
                if sys.platform == "darwin":
                    fallback = self.output_dir / output_name
                    if fallback.exists():
                        final_path = fallback
                    else:
                        raise FileNotFoundError("Output executable not found")
                else:
                    raise FileNotFoundError("Output executable not found")

        logger.info(f"Build complete: {final_path}")
        return final_path


def main():
    parser = argparse.ArgumentParser(description="CodeVault Cloud Runner")
    parser.add_argument("--config", required=True, help="JSON config string")
    parser.add_argument("--source", required=True, help="Source directory")
    args = parser.parse_args()

    try:
        config = json.loads(args.config)
        source_dir = Path(args.source).resolve()

        # Use platform-specific output dir to avoid collisions in parallel Cloud Build steps
        platform_suffix = sys.platform

        # Detect Wine environment (sys.platform is 'win32' in Wine)
        if sys.platform == "win32" or os.environ.get("WINEPREFIX"):
            # Cloud Build expects 'build_output_windows_wine'
            platform_suffix = "windows_wine"
        elif sys.platform == "linux":
            # Standardize Linux output directory name
            platform_suffix = "linux"

        output_dir = source_dir / f"build_output_{platform_suffix}"
        output_dir.mkdir(exist_ok=True)

        runner = CloudRunner(source_dir, output_dir, config)
        exe_path = runner.run()

        # Output result for GH Actions (using new GITHUB_OUTPUT environment variable)
        if "GITHUB_OUTPUT" in os.environ:
            with open(os.environ["GITHUB_OUTPUT"], "a") as f:
                f.write(f"exe_path={exe_path}\n")
        else:
            # Fallback for local testing
            print(f"::set-output name=exe_path::{exe_path}")

    except Exception as e:
        logger.error(f"Build failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
