#!/usr/bin/env python3
"""
CodeVault Cloud Build Runner for Node.js
Standalone script to execute pkg builds in CI/CD environments.
Supports single-file and project-based Node.js builds.
"""

import os
import sys
import json
import logging
import subprocess
import argparse
import re
from pathlib import Path

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - [NodeRunner] - %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)


class NodeJSBuilder:
    """Build Node.js projects using @yao-pkg/pkg"""

    def __init__(self, config: dict, source_dir: Path):
        self.config = config
        self.source_dir = source_dir
        self.project_name = config.get("project_name", "app")
        self.output_name = config.get("output_name", "app")
        self.entry_file = config.get("entry_file", "index.js")
        self.license_key = config.get("license_key", "GENERIC_BUILD")
        self.target_platforms = config.get("target_platforms", ["windows"])
        self.api_url = config.get("api_url", "")

    def prepare_package_json(self) -> bool:
        """Prepare package.json for pkg, creating if needed"""
        package_json_path = self.source_dir / "package.json"

        # If package.json exists, we need to update it
        if package_json_path.exists():
            try:
                with open(package_json_path, "r", encoding="utf-8") as f:
                    pkg_data = json.load(f)
            except Exception as e:
                logger.warning(f"Could not parse existing package.json: {e}")
                pkg_data = {}
        else:
            pkg_data = {}

        # Ensure 'main' points to entry file
        pkg_data["main"] = self.entry_file

        # Set name if not present
        if "name" not in pkg_data:
            pkg_data["name"] = (
                self.output_name.lower().replace("-", "_").replace(" ", "_")
            )

        # Set version if not present
        if "version" not in pkg_data:
            pkg_data["version"] = "1.0.0"

        # Add pkg configuration for binary output
        pkg_data["pkg"] = {
            "outputPath": ".",
            "targets": ["node20-win-x64"],
            "assets": [],
        }

        # Write updated package.json
        try:
            with open(package_json_path, "w", encoding="utf-8") as f:
                json.dump(pkg_data, f, indent=2)
            logger.info(f"Created/updated package.json with main: {self.entry_file}")
            return True
        except Exception as e:
            logger.error(f"Failed to write package.json: {e}")
            return False

    def inject_license_protection(self) -> bool:
        """Inject license protection into entry file"""
        entry_path = self.source_dir / self.entry_file

        if not entry_path.exists():
            logger.error(f"Entry file not found: {self.entry_file}")
            return False

        try:
            with open(entry_path, "r", encoding="utf-8") as f:
                original_code = f.read()

            # Check if already protected
            if "CODEVAULT LICENSE PROTECTION" in original_code:
                logger.info("Entry file already has license protection")
                return True

            # Generate license protection wrapper
            license_wrapper = self._generate_license_wrapper()

            # Prepend wrapper to original code
            protected_code = license_wrapper + "\n\n" + original_code

            with open(entry_path, "w", encoding="utf-8") as f:
                f.write(protected_code)

            logger.info("Injected license protection into entry file")
            return True

        except Exception as e:
            logger.error(f"Failed to inject license protection: {e}")
            return False

    def _generate_license_wrapper(self) -> str:
        """Generate license protection wrapper for Node.js"""
        return f'''// ============ CODEVAULT LICENSE PROTECTION ============
// This code protects your application with license validation
// Generated by CodeVault (codevault.app)
// Features: License key validation, Heartbeat

const _cv_LICENSE_KEY = "{self.license_key}";
const _cv_SERVER_URL = "{self.api_url}";
const _cv_APP_NAME = "{self.project_name}";
const _cv_HEARTBEAT_INTERVAL = 3600000; // 1 hour in ms

// License validation
async function _cv_validateLicense() {{
    if (_cv_LICENSE_KEY === "GENERIC_BUILD") {{
        return true; // Skip validation for generic builds
    }}
    
    try {{
        const https = require('https');
        const os = require('os');
        
        const body = JSON.stringify({{
            license_key: _cv_LICENSE_KEY,
            machine_id: os.hostname() + '-' + os.cpus()[0].model,
            app_name: _cv_APP_NAME
        }});
        
        return new Promise((resolve) => {{
            const req = https.request(_cv_SERVER_URL, {{
                method: 'POST',
                headers: {{ 'Content-Type': 'application/json' }}
            }}, (res) => {{
                let data = '';
                res.on('data', chunk => data += chunk);
                res.on('end', () => {{
                    try {{
                        const result = JSON.parse(data);
                        resolve(result.valid === true);
                    }} catch {{
                        resolve(false);
                    }}
                }});
            }});
            req.on('error', () => resolve(false));
            req.write(body);
            req.end();
        }});
    }} catch {{
        return false;
    }}
}}

// Heartbeat
let _cv_heartbeatTimer = null;
async function _cv_startHeartbeat() {{
    if (_cv_LICENSE_KEY === "GENERIC_BUILD") return;
    
    _cv_heartbeatTimer = setInterval(async () => {{
        try {{
            await _cv_validateLicense();
        }} catch {{}}
    }}, _cv_HEARTBEAT_INTERVAL);
}}

// Run validation before main code
async function _cv_init() {{
    const valid = await _cv_validateLicense();
    if (!valid && _cv_LICENSE_KEY !== "GENERIC_BUILD") {{
        console.error("\\n" + "=".repeat(60));
        console.error("  [LICENSE ERROR] Invalid or expired license");
        console.error("  App: " + _cv_APP_NAME);
        console.error("  Please contact support");
        console.error("=".repeat(60) + "\\n");
        process.exit(1);
    }}
    _cv_startHeartbeat();
}}

// Start validation (will be awaited before main code runs)
// For pkg compatibility, we sync-validate at startup
if (_cv_LICENSE_KEY !== "GENERIC_BUILD") {{
    const valid = require('child_process').spawnSync('node', ['-e', `
        const https = require('https');
        const os = require('os');
        const body = JSON.stringify({{
            license_key: "${self.license_key}",
            machine_id: os.hostname(),
            app_name: "${self.project_name}"
        }});
        const req = https.request("${self.api_url}", {{
            method: 'POST',
            headers: {{ 'Content-Type': 'application/json' }}
        }}, (res) => {{
            let data = '';
            res.on('data', c => data += c);
            res.on('end', () => {{
                try {{ console.log(JSON.parse(data).valid ? '1' : '0'); }}
                catch {{ console.log('0'); }}
            }});
        }});
        req.on('error', () => console.log('0'));
        req.write(body);
        req.end();
    `], {{ encoding: 'utf8' }});
    
    if (valid.stdout.trim() !== '1') {{
        console.error("\\n" + "=".repeat(60));
        console.error("  [LICENSE ERROR] Invalid or expired license");
        console.error("  App: ${self.project_name}");
        console.error("=".repeat(60) + "\\n");
        process.exit(1);
    }}
}}
// ============ END LICENSE PROTECTION ============
'''

    def install_dependencies(self) -> bool:
        """Install npm dependencies"""
        package_json_path = self.source_dir / "package.json"

        if not package_json_path.exists():
            logger.warning("No package.json found, skipping npm install")
            return True

        try:
            logger.info("Installing npm dependencies...")
            result = subprocess.run(
                ["npm", "install", "--quiet", "--production"],
                cwd=str(self.source_dir),
                capture_output=True,
                text=True,
                timeout=300,
            )

            if result.returncode != 0:
                logger.warning(f"npm install had issues: {result.stderr}")
                # Continue anyway, might be optional deps

            logger.info("Dependencies installed")
            return True
        except Exception as e:
            logger.error(f"Failed to install dependencies: {e}")
            return False

    def build_targets(self) -> dict:
        """Build for all target platforms"""
        results = {}

        # Map target platforms to pkg targets
        target_map = {
            "windows": "node20-win-x64",
            "linux": "node20-linux-x64",
            "macos": "node20-macos-x64",
        }

        for platform in self.target_platforms:
            pkg_target = target_map.get(platform)
            if not pkg_target:
                logger.warning(f"Unknown platform: {platform}")
                continue

            logger.info(f"Building for {platform} ({pkg_target})...")
            success = self._build_single_target(pkg_target, platform)
            results[platform] = "completed" if success else "failed"

        return results

    def _build_single_target(self, pkg_target: str, platform: str) -> bool:
        """Build for a single target platform"""
        output_dir = self.source_dir / f"build_output_{platform}"
        output_dir.mkdir(parents=True, exist_ok=True)

        # Determine output filename
        if platform == "windows":
            output_filename = f"{self.output_name}.exe"
        elif platform == "macos":
            output_filename = self.output_name
        else:
            output_filename = self.output_name

        try:
            # Build pkg command
            cmd = [
                "npx",
                "@yao-pkg/pkg",
                ".",
                "--target",
                pkg_target,
                "--output",
                output_filename,
                "--out-path",
                str(output_dir),
                "--no-bytecode",  # For better compatibility
                "--public",  # Allow public packages
            ]

            # Add config if exists
            package_json = self.source_dir / "package.json"
            if package_json.exists():
                cmd.extend(["--config", str(package_json)])

            logger.info(f"Running: {' '.join(cmd)}")

            result = subprocess.run(
                cmd,
                cwd=str(self.source_dir),
                capture_output=True,
                text=True,
                timeout=600,
            )

            if result.returncode != 0:
                logger.error(f"pkg build failed: {result.stderr}")
                return False

            # Verify output
            output_path = output_dir / output_filename
            if output_path.exists():
                size_kb = output_path.stat().st_size / 1024
                logger.info(f"Build complete: {output_filename} ({size_kb:.1f} KB)")
                return True
            else:
                logger.error(f"Output not found: {output_path}")
                return False

        except subprocess.TimeoutExpired:
            logger.error("Build timed out")
            return False
        except Exception as e:
            logger.error(f"Build error: {e}")
            return False

    def run(self) -> bool:
        """Execute the full build process"""
        logger.info(f"Starting Node.js build for: {self.project_name}")
        logger.info(f"Entry file: {self.entry_file}")
        logger.info(f"Output name: {self.output_name}")
        logger.info(f"Target platforms: {self.target_platforms}")

        # Step 1: Prepare package.json
        if not self.prepare_package_json():
            return False

        # Step 2: Inject license protection
        if self.license_key != "GENERIC_BUILD":
            if not self.inject_license_protection():
                logger.warning(
                    "License protection injection failed, continuing without"
                )

        # Step 3: Install dependencies
        if not self.install_dependencies():
            logger.warning("Dependency installation had issues, continuing anyway")

        # Step 4: Build for each target
        results = self.build_targets()

        # Check if at least one succeeded
        success = any(s == "completed" for s in results.values())

        if success:
            logger.info("Build completed successfully")
        else:
            logger.error("All builds failed")

        return success


def main():
    parser = argparse.ArgumentParser(description="CodeVault Node.js Build Runner")
    parser.add_argument("--config", required=True, help="JSON config string")
    parser.add_argument("--source", required=True, help="Source directory path")

    args = parser.parse_args()

    # Parse config
    try:
        config = json.loads(args.config)
    except json.JSONDecodeError as e:
        logger.error(f"Invalid config JSON: {e}")
        sys.exit(1)

    # Validate source directory
    source_dir = Path(args.source)
    if not source_dir.exists():
        logger.error(f"Source directory not found: {source_dir}")
        sys.exit(1)

    # Run builder
    builder = NodeJSBuilder(config, source_dir)
    success = builder.run()

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
