"""
Unified License Wrapper Template for CodeVault

This template combines the best features from CLI, Server, and Cloud Build versions:
- Startup pop-up showing protection status (Phase 2.1)
- Unified license dialog with better error handling (Phase 2.2)
- Ed25519 signature verification for security
- Heartbeat for floating licenses
- Offline lease support (24h)
- Better HWID generation with MAC address
- Fall back to file logging when GUI unavailable

Usage:
    from unified_license_wrapper import get_license_wrapper

    wrapper = get_license_wrapper(
        license_key="LIC-XXXX-XXXX",
        server_url="https://api.codevault.app",
        lease_enabled=True,
        public_key="...",
        heartbeat_interval=300,
        app_name="My App"
    )
"""

UNIFIED_LICENSE_WRAPPER_TEMPLATE = r'''# ============ CODEVAULT LICENSE PROTECTION ============
# This code protects your application with license validation
# Generated by CodeVault (codevault.app)

import sys as _cv_sys
import os as _cv_os
import hashlib as _cv_hash
import json as _cv_json
import time as _cv_time
import platform as _cv_platform
import base64 as _cv_base64
import uuid as _cv_uuid
import re as _cv_re
import atexit as _cv_atexit
from pathlib import Path as _cv_Path

# Configuration - Do not modify these values directly
_CV_LICENSE_KEY = "{license_key}"
_CV_SERVER_URL = "{server_url}"
_CV_LEASE_ENABLED = {lease_enabled}
_CV_PUBLIC_KEY = """{public_key}"""
_CV_BINARY_HASH = "{binary_hash}"
_CV_HEARTBEAT_INTERVAL = {heartbeat_interval}
_CV_APP_NAME = "{app_name}"
_CV_SHOW_BRANDING = {show_branding}
_CV_BRAND_NAME = "{brand_name}"
_CV_BRAND_URL = "{brand_url}"
_CV_BRAND_PRIMARY_COLOR = "{brand_primary_color}"

# Lease configuration
_CV_LEASE_DURATION = 24 * 60 * 60  # 24 hours in seconds
_CV_CLOCK_DRIFT_MAX = 60 * 60  # 1 hour max drift

# Floating license session tracking
_CV_SESSION_TOKEN = None

# DEPRECATION WARNING for HMAC projects
if not _CV_PUBLIC_KEY:
    print("[CodeVault] WARNING: Legacy HMAC project detected. This project uses deprecated security.")
    print("[CodeVault] Please migrate to Ed25519 for enhanced security.")
    print("[CodeVault] Contact support for migration assistance.")

# =============================================================================
# STARTUP POP-UP - Shows protection status on launch
# =============================================================================

def _cv_show_startup_popup():
    """
    Show startup pop-up indicating the application is protected.
    This runs before any user code and provides visual confirmation
    that the protection is active.
    """
    try:
        import tkinter as tk
        from tkinter import ttk
        
        root = tk.Tk()
        root.title(f"{_CV_APP_NAME} - Protected Application")
        root.geometry("450x200")
        root.resizable(False, False)
        root.configure(bg="#1a1a2e")
        root.overrideredirect(True)  # No window decorations
        root.attributes('-topmost', True)
        
        # Center on screen
        root.update_idletasks()
        screen_width = root.winfo_screenwidth()
        screen_height = root.winfo_screenheight()
        x = (screen_width - 450) // 2
        y = (screen_height - 200) // 2
        root.geometry(f"450x200+{x}+{y}")
        
        # Main frame
        main_frame = tk.Frame(root, bg="#1a1a2e", padx=30, pady=20)
        main_frame.pack(fill=tk.BOTH, expand=True)
        
        # Branding (for free tier or custom branding)
        if _CV_SHOW_BRANDING:
            brand_text = f"Protected by {_CV_BRAND_NAME}"
            branding = tk.Label(main_frame, text=brand_text,
                font=("Segoe UI", 9),
                fg="#888888",
                bg="#1a1a2e"
            )
            branding.pack(pady=(0, 5))
        
        # App name
        app_label = tk.Label(main_frame, text=_CV_APP_NAME,
                            font=("Segoe UI", 16, "bold"), fg="#ffffff", bg="#1a1a2e")
        app_label.pack(pady=(0, 10))
        
        # Status line
        status_frame = tk.Frame(main_frame, bg="#1a1a2e")
        status_frame.pack(fill=tk.X)
        
        # Check current license status
        if _CV_LICENSE_KEY == "DEMO":
            status_text = "DEMO MODE - Time Limited"
            status_color = "#ffa500"
        else:
            status_text = "License Protected"
            status_color = "#00d4aa"
        
        status_label = tk.Label(status_frame, text=f"● {status_text}",
                               font=("Segoe UI", 10, "bold"),
                               fg=status_color, bg="#1a1a2e")
        status_label.pack(side=tk.LEFT)
        
        # Progress bar
        progress = ttk.Progressbar(main_frame, mode='indeterminate', length=380)
        progress.pack(pady=(20, 10))
        progress.start(10)
        
        # Click anywhere to dismiss (or auto-close after 2s)
        def close_splash():
            try:
                root.destroy()
            except:
                pass
        
        root.bind('<Button-1>', lambda e: close_splash())
        root.after(2000, close_splash)
        
        # Run
        root.mainloop()
        
    except ImportError:
        # tkinter not available - use console
        if _CV_LICENSE_KEY == "DEMO":
            print(f"\n[CodeVault] {_CV_APP_NAME} - DEMO MODE")
        else:
            print(f"\n[CodeVault] {_CV_APP_NAME} - License Protected")
        _cv_time.sleep(0.5)
    except Exception:
        # Silently ignore splash errors
        pass

# Show splash immediately on import
_cv_show_startup_popup()

# =============================================================================
# ERROR DISPLAY - GUI and console fallback
# =============================================================================

def _cv_show_error(title, message, details=None, is_fatal=True):
    """
    Display error to user with both GUI and console fallback.
    Ensures error is visible even in --onefile mode.
    """
    # Try GUI first
    try:
        import tkinter as tk
        from tkinter import messagebox
        
        root = tk.Tk()
        root.withdraw()
        root.attributes('-topmost', True)
        
        # Build full error message
        full_message = message
        if details:
            full_message += f"\n\nDetails: {details}"
        
        full_message += "\n\nTroubleshooting:"
        if "LICENSE INVALID" in title:
            full_message += "\n- Check license key for typos"
            full_message += "\n- Ensure license is active"
            full_message += "\n- Verify internet connection"
        elif "CONNECTION" in title or "OFFLINE" in title:
            full_message += "\n- Check internet connection"
            full_message += "\n- Contact support for offline mode"
        else:
            full_message += "\n- Take screenshot of this error"
            full_message += "\n- Contact support for assistance"
        
        messagebox.showerror(title, full_message)
        root.destroy()
        
        if is_fatal:
            _cv_sys.exit(1)
        return
        
    except Exception:
        # GUI failed, use console
        pass
    
    # Console fallback
    print("\n" + "=" * 60)
    print(f"  [ERROR] {title}")
    print("=" * 60)
    print(f"\n{message}")
    if details:
        print(f"\nDetails: {details}")
    print("\nTroubleshooting:")
    if "LICENSE INVALID" in title:
        print("- Check license key for typos")
        print("- Ensure license is active")
        print("- Verify internet connection")
    elif "CONNECTION" in title or "OFFLINE" in title:
        print("- Check internet connection")
        print("- Contact support for offline mode")
    else:
        print("- Take screenshot of this error")
        print("- Contact support for assistance")
    print("=" * 60)
    
    # Log to file
    try:
        log_path = _cv_Path(_cv_os.path.expanduser("~")) / ".codevault" / "errors.log"
        log_path.parent.mkdir(exist_ok=True)
        with open(log_path, 'a', encoding='utf-8') as f:
            f.write(f"\n[{_cv_time.strftime('%Y-%m-%d %H:%M:%S')}] {title}\n")
            f.write(f"Message: {message}\n")
            if details:
                f.write(f"Details: {details}\n")
            f.write("-" * 60 + "\n")
    except:
        pass
    
    if is_fatal:
        try:
            input("\nPress Enter to exit...")
        except:
            pass
        _cv_sys.exit(1)

def _cv_show_info(title, message):
    """Show information dialog."""
    try:
        import tkinter as tk
        from tkinter import messagebox
        
        root = tk.Tk()
        root.withdraw()
        root.attributes('-topmost', True)
        messagebox.showinfo(title, message)
        root.destroy()
    except:
        print(f"\n[{title}] {message}")

# =============================================================================
# LICENSE DIALOG - Unified GUI with console fallback
# =============================================================================

class _CV_LicenseDialog:
    """Modern license activation dialog using tkinter"""
    
    def __init__(self):
        try:
            import tkinter as tk
            from tkinter import ttk
            self.tk = tk
            self.ttk = ttk
            self.has_tkinter = True
        except ImportError:
            self.has_tkinter = False
            return
        
        self.result = None
        self.validating = False
        self.root = None
    
    def show(self):
        """Show the license dialog and return the entered key."""
        if not self.has_tkinter:
            return None
        
        tk = self.tk
        self.root = tk.Tk()
        self.root.title(f"{_CV_APP_NAME} - License Activation")
        
        # Window size and position
        win_w, win_h = 480, 320
        self.root.geometry(f"{win_w}x{win_h}")
        self.root.resizable(False, False)
        self.root.configure(bg="#1a1a2e")
        
        # Center on screen
        self.root.update_idletasks()
        try:
            sx = (self.root.winfo_screenwidth() - win_w) // 2
            sy = (self.root.winfo_screenheight() - win_h) // 2
            self.root.geometry(f"{win_w}x{win_h}+{sx}+{sy}")
        except:
            pass
        
        # Main container
        main = tk.Frame(self.root, bg="#1a1a2e", padx=40, pady=30)
        main.pack(fill=tk.BOTH, expand=True)
        
        # Branding (for free tier)
        if _CV_SHOW_BRANDING:
            branding = tk.Label(main, text="Protected by CodeVault",
                               font=("Segoe UI", 9), fg="#888888", bg="#1a1a2e")
            branding.pack(pady=(0, 10))
        
        # Title
        tk.Label(main, text="License Activation",
                font=("Segoe UI", 18, "bold"), fg="#e94560",
                bg="#1a1a2e", anchor="center").pack(fill=tk.X, pady=(0, 5))
        
        # Subtitle
        tk.Label(main, text="Enter your license key to activate this application",
                font=("Segoe UI", 10), fg="#aaaaaa",
                bg="#1a1a2e", anchor="center").pack(fill=tk.X, pady=(0, 25))
        
        # Input field
        border = tk.Frame(main, bg="#2a2a4a", padx=2, pady=2)
        border.pack(fill=tk.X, pady=(0, 20))
        
        self.license_entry = tk.Entry(border, font=("Consolas", 13),
                                     bg="#0f0f23", fg="#ffffff",
                                     insertbackground="#e94560",
                                     relief=tk.FLAT)
        self.license_entry.pack(fill=tk.X, ipady=10, padx=1, pady=1)
        self.license_entry.focus_set()
        self.license_entry.bind("<Return>", lambda e: self.activate())
        
        # Activate button
        self.activate_btn = tk.Button(main, text="Activate License",
                                     font=("Segoe UI", 12, "bold"),
                                     bg="#e94560", fg="white",
                                     activebackground="#c73e54",
                                     activeforeground="white",
                                     relief=tk.FLAT, cursor="hand2",
                                     bd=0, command=self.activate)
        self.activate_btn.pack(fill=tk.X, ipady=10, pady=(0, 15))
        
        # Status label
        self.status_label = tk.Label(main, text="", font=("Segoe UI", 9),
                                    fg="#888888", bg="#1a1a2e")
        self.status_label.pack()
        
        # Bind close
        self.root.protocol("WM_DELETE_WINDOW", self.on_close)
        
        # Run
        try:
            self.root.mainloop()
        except KeyboardInterrupt:
            self.on_close()
        
        return self.result
    
    def set_status(self, message, color="#888888"):
        """Update status label."""
        if not self.root:
            return
        try:
            self.status_label.configure(text=message, fg=color)
            self.root.update()
        except:
            pass
    
    def activate(self):
        """Handle activation button click."""
        if self.validating:
            return
        try:
            license_key = self.license_entry.get().strip()
            if not license_key:
                self.set_status("Please enter a license key", "#ffaa00")
                return
            
            self.validating = True
            self.activate_btn.configure(state=self.tk.DISABLED, text="Validating...")
            self.set_status("Connecting to server...", "#4a90d9")
            
            self.result = license_key
            self.root.destroy()
        except:
            self.validating = False
    
    def on_close(self):
        """Handle window close."""
        if not self.validating:
            self.result = None
            try:
                self.root.destroy()
            except:
                pass

# =============================================================================
# HARDWARE ID - Robust HWID generation
# =============================================================================

def _cv_get_hwid():
    """
    Generate robust hardware ID for license validation.
    Uses MAC address and system info for stability.
    """
    try:
        # Get MAC address
        mac = ":".join(_cv_re.findall("..", "%012x" % _cv_uuid.getnode()))
        
        # Combine system info
        info = f"""{_cv_platform.node()}|
                   {_cv_platform.system()}|
                   {_cv_platform.machine()}|
                   {_cv_platform.processor()}|
                   {mac}"""
        return _cv_hash.sha256(info.encode()).hexdigest()[:32]
    except Exception as e:
        # Fallback to basic info
        try:
            info = f"{_cv_platform.node()}|{_cv_platform.system()}|{_cv_platform.machine()}"
            return _cv_hash.sha256(info.encode()).hexdigest()[:32]
        except:
            return "unknown-hwid"

def _cv_get_binary_hash():
    """Calculate SHA-256 hash of current executable for integrity checking."""
    try:
        if getattr(_cv_sys, 'frozen', False):
            path = _cv_sys.executable
        else:
            path = _cv_sys.argv[0]
        
        sha256 = _cv_hash.sha256()
        with open(path, "rb") as f:
            for byte_block in iter(lambda: f.read(4096), b""):
                sha256.update(byte_block)
        return sha256.hexdigest()
    except Exception:
        return None

def _cv_verify_binary_integrity():
    """Verify binary hasn't been tampered with."""
    if not _CV_BINARY_HASH or _CV_BINARY_HASH == "skip":
        return True
    
    try:
        actual_hash = _cv_get_binary_hash()
        if actual_hash and actual_hash != _CV_BINARY_HASH:
            _cv_show_error(
                "Binary Tampered",
                "The executable has been modified or corrupted.",
                "This may indicate tampering. Please re-download the application."
            )
            return False
        return True
    except Exception as e:
        print(f"[CodeVault] Warning: Could not verify binary integrity: {e}")
        return True

# =============================================================================
# FILE PATHS - License and lease file paths
# =============================================================================

def _cv_get_license_key_path():
    """Get path to license.key file with fallback to home directory."""
    try:
        # Get base directory
        if getattr(_cv_sys, 'frozen', False):
            base_dir = _cv_Path(_cv_sys.executable).parent
        else:
            base_dir = _cv_Path(_cv_os.path.abspath(__file__)).parent
        
        # Try base directory first
        key_path = base_dir / "license.key"
        
        # Test writability
        try:
            test_file = base_dir / ".cv_write_test"
            test_file.write_text("test")
            test_file.unlink()
            return str(key_path)
        except:
            # Fall back to home directory
            home_dir = _cv_Path.home()
            app_dir = home_dir / ".codevault"
            app_dir.mkdir(exist_ok=True)
            return str(app_dir / "license.key")
    except:
        return str(_cv_Path.home() / ".codevault" / "license.key")

def _cv_get_lease_path():
    """Get path to license.lease file."""
    key_path = _cv_get_license_key_path()
    return str(_cv_Path(key_path).parent / "license.lease")

# =============================================================================
# ENCRYPTION - Lease encryption/decryption
# =============================================================================

def _cv_get_machine_secret():
    """Generate machine-specific secret for encryption."""
    try:
        info = f"{_cv_platform.node()}|{_cv_platform.machine()}|{_cv_platform.processor()}|CV_SALT_2026"
        return _cv_hash.sha256(info.encode()).digest()
    except:
        return _cv_hash.sha256(b"fallback_secret_key").digest()

def _cv_encrypt_lease(lease_data):
    """Encrypt lease data with AES-256-GCM."""
    try:
        secret = _cv_get_machine_secret()
        data_json = _cv_json.dumps(lease_data).encode('utf-8')
        
        try:
            from cryptography.hazmat.primitives.ciphers.aead import AESGCM
            import secrets as _secrets
            nonce = _secrets.token_bytes(12)
            aesgcm = AESGCM(secret)
            ciphertext = aesgcm.encrypt(nonce, data_json, None)
            return _cv_base64.b64encode(b"AES:" + nonce + ciphertext).decode()
        except ImportError:
            # Cryptography not available
            return None
    except Exception:
        return None

def _cv_decrypt_lease(encrypted_data):
    """Decrypt lease data (AES-256-GCM)."""
    try:
        secret = _cv_get_machine_secret()
        raw = _cv_base64.b64decode(encrypted_data)
        
        if raw.startswith(b"AES:"):
            try:
                from cryptography.hazmat.primitives.ciphers.aead import AESGCM
                nonce = raw[4:16]
                ciphertext = raw[16:]
                aesgcm = AESGCM(secret)
                data_json = aesgcm.decrypt(nonce, ciphertext, None)
                return _cv_json.loads(data_json.decode('utf-8'))
            except:
                return None
        else:
            return None
    except:
        return None

def _cv_create_lease(license_key, hwid, server_time):
    """Create new lease token."""
    return {
        "license_key_hash": _cv_hash.sha256(license_key.encode()).hexdigest(),
        "hwid": hwid,
        "expires_at": server_time + _CV_LEASE_DURATION,
        "server_time": server_time,
        "validated_at": int(_cv_time.time())
    }

def _cv_save_lease(lease_data):
    """Save encrypted lease to file."""
    if not _CV_LEASE_ENABLED:
        return False
    try:
        lease_path = _cv_get_lease_path()
        encrypted = _cv_encrypt_lease(lease_data)
        if encrypted:
            _cv_Path(lease_path).write_text(encrypted, encoding='utf-8')
            return True
    except:
        pass
    return False

def _cv_load_lease():
    """Load and decrypt lease from file."""
    if not _CV_LEASE_ENABLED:
        return None
    try:
        lease_path = _cv_get_lease_path()
        if _cv_Path(lease_path).exists():
            encrypted = _cv_Path(lease_path).read_text(encoding='utf-8').strip()
            return _cv_decrypt_lease(encrypted)
    except:
        pass
    return None

def _cv_validate_lease(license_key):
    """Validate existing lease."""
    if not _CV_LEASE_ENABLED:
        return False, "Offline mode not enabled"
    
    lease = _cv_load_lease()
    if not lease:
        return False, "No lease found"
    
    hwid = _cv_get_hwid()
    current_time = int(_cv_time.time())
    
    if lease.get("hwid") != hwid:
        return False, "HWID mismatch - lease invalid on this machine"
    
    key_hash = _cv_hash.sha256(license_key.encode()).hexdigest()
    if lease.get("license_key_hash") != key_hash:
        return False, "License key mismatch"
    
    expires_at = lease.get("expires_at", 0)
    if current_time > expires_at:
        return False, "Lease expired"
    
    remaining = expires_at - current_time
    hours = remaining // 3600
    mins = (remaining % 3600) // 60
    return True, f"Lease valid ({hours}h {mins}m remaining)"

# =============================================================================
# HEARTBEAT - Background license check
# =============================================================================

def _cv_start_heartbeat(license_key, hwid, interval, session_token=None):
    """Start background heartbeat thread for floating licenses."""
    try:
        import threading as _threading
        
        def heartbeat_loop():
            while True:
                _cv_time.sleep(interval)
                try:
                    import urllib.request
                    
                    payload_data = {
                        "license_key": license_key,
                        "hwid": hwid,
                        "timestamp": int(_cv_time.time())
                    }
                    # Phase 3: Include session_token for floating license heartbeat
                    if session_token:
                        payload_data["session_token"] = session_token
                    
                    payload = _cv_json.dumps(payload_data).encode('utf-8')
                    
                    req = urllib.request.Request(
                        _CV_SERVER_URL + "/api/v1/license/heartbeat",
                        data=payload,
                        headers={"Content-Type": "application/json"}
                    )
                    
                    with urllib.request.urlopen(req, timeout=10) as resp:
                        pass
                except:
                    pass
        
        t = _threading.Thread(target=heartbeat_loop, daemon=True)
        t.start()
    except:
        pass

def _cv_release_session():
    """Release floating license session on exit."""
    global _CV_SESSION_TOKEN
    if not _CV_SESSION_TOKEN:
        return
    try:
        import urllib.request
        
        hwid = _cv_get_hwid()
        payload = _cv_json.dumps({
            "session_token": _CV_SESSION_TOKEN,
            "hwid": hwid
        }).encode('utf-8')
        
        req = urllib.request.Request(
            _CV_SERVER_URL + "/api/v1/license/release",
            data=payload,
            headers={"Content-Type": "application/json"}
        )
        
        with urllib.request.urlopen(req, timeout=5) as resp:
            pass
    except:
        pass

# =============================================================================
# LICENSE VALIDATION - Main validation logic
# =============================================================================

def _cv_load_or_prompt_license():
    """Load license from file or prompt user."""
    license_path = _cv_get_license_key_path()
    
    # Try to load saved license
    if _cv_Path(license_path).exists():
        try:
            key = _cv_Path(license_path).read_text(encoding='utf-8').strip()
            if key:
                return key
        except:
            pass
    
    # Prompt for license
    dialog = _CV_LicenseDialog()
    key = dialog.show()
    
    if not key:
        _cv_show_error("NO LICENSE KEY", 
                      "No license key was provided.",
                      "The application requires a valid license key to run.")
    
    # Save license
    try:
        _cv_Path(license_path).write_text(key, encoding='utf-8')
    except:
        pass
    
    return key

def _cv_validate_signature(result):
    """Verify Ed25519 signature from server response."""
    server_sig = result.get("signature")
    if not server_sig:
        _cv_show_error("SECURITY ERROR", 
                      "Server response is unsigned.",
                      "Response missing digital signature.")
        return False
    
    if not _CV_PUBLIC_KEY or not _CV_PUBLIC_KEY.strip():
        _cv_show_error("SECURITY ERROR",
                      "No public key configured.",
                      "Cannot verify server response without a public key.")
        return False
    
    # Reconstruct canonical message
    features_json = _cv_json.dumps(sorted(result.get("features", [])), sort_keys=True)
    variables_json = _cv_json.dumps(result.get("variables", {}), sort_keys=True)
    
    msg = "|".join(str(v) for v in [
        result.get("status", ""),
        result.get("expires_at", "") or "",
        features_json,
        variables_json,
        result.get("client_nonce", ""),
        result.get("server_nonce", ""),
        result.get("timestamp", ""),
        result.get("server_time", "")
    ])
    
    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
        from cryptography.hazmat.primitives.serialization import load_pem_public_key
        
        pub_key = load_pem_public_key(_CV_PUBLIC_KEY.encode())
        sig_bytes = _cv_base64.b64decode(server_sig)
        pub_key.verify(sig_bytes, msg.encode())
        return True
    except Exception as e:
        _cv_show_error("SECURITY ERROR",
                      "Server signature verification failed.",
                      f"The response may be tampered. Error: {e}")
        return False

def _cv_validate_license():
    """Main license validation function."""
    global _CV_SESSION_TOKEN
    
    # Handle DEMO mode - NOT allowed in production builds
    if _CV_LICENSE_KEY == "DEMO":
        print("[CodeVault] DEMO mode not allowed in production builds")
        _cv_sys.exit(1)
    
    # Handle GENERIC_BUILD mode (runtime prompt)
    license_key = _CV_LICENSE_KEY
    if _CV_LICENSE_KEY == "GENERIC_BUILD":
        license_key = _cv_load_or_prompt_license()
    
    hwid = _cv_get_hwid()
    
    # Build validation request
    try:
        import urllib.request
        import urllib.error
        
        nonce = _cv_hash.sha256(str(_cv_time.time()).encode()).hexdigest()[:32]
        
        payload = _cv_json.dumps({
            "license_key": license_key,
            "hwid": hwid,
            "machine_name": _cv_platform.node(),
            "nonce": nonce,
            "timestamp": int(_cv_time.time()),
            "binary_hash": _cv_get_binary_hash()
        }).encode('utf-8')
        
        req = urllib.request.Request(
            _CV_SERVER_URL + "/api/v1/license/validate",
            data=payload,
            headers={"Content-Type": "application/json"},
            timeout=15
        )
        
        with urllib.request.urlopen(req) as resp:
            result = _cv_json.loads(resp.read().decode('utf-8'))
            
            # Verify signature
            if not _cv_validate_signature(result):
                return False
            
            # Protocol v2: Verify response freshness
            issued_at = result.get("issued_at")
            if issued_at:
                import time as _cv_time_pkg
                current_time = int(_cv_time_pkg.time())
                response_age = current_time - issued_at
                if response_age > 300:
                    _cv_show_error("SECURITY ERROR",
                                  "Response expired.",
                                  f"Server response is too old ({response_age}s). Possible replay attack.")
                    return False
                if response_age < -60:
                    _cv_show_error("SECURITY ERROR",
                                  "Response from future.",
                                  "Clock skew detected. Please correct your system time.")
                    return False
            
            # Protocol v2: Require jti for replay protection
            if not result.get("jti"):
                _cv_show_error("SECURITY ERROR",
                              "Missing replay protection.",
                              "Server response missing jti (replay protection ID).")
                return False
            
            if result.get("status") == "valid":
                # Start heartbeat
                _cv_start_heartbeat(license_key, hwid, _CV_HEARTBEAT_INTERVAL, _CV_SESSION_TOKEN)
                
                # Register session release
                _atexit.register(_cv_release_session)
                
                # Save session token
                _CV_SESSION_TOKEN = result.get("variables", {}).get("_cv_session_token")
                
                # Check clock drift and save lease
                server_time = result.get("server_time", result.get("timestamp", int(_cv_time.time())))
                local_time = int(_cv_time.time())
                drift = abs(local_time - server_time)
                
                if drift > _CV_CLOCK_DRIFT_MAX:
                    print(f"[CodeVault] Clock drift detected: {drift}s")
                else:
                    lease = _cv_create_lease(license_key, hwid, server_time)
                    _cv_save_lease(lease)
                
                return True
            else:
                # License invalid
                msg = result.get("message", "License invalid")
                
                # Remove saved license
                try:
                    _cv_Path(_cv_get_license_key_path()).unlink(missing_ok=True)
                    _cv_Path(_cv_get_lease_path()).unlink(missing_ok=True)
                except:
                    pass
                
                _cv_show_error("LICENSE INVALID",
                              "The license key was rejected by the server.",
                              f"Server message: {msg}")
                return False
    
    except Exception as e:
        # Connection failed - try offline lease
        error_msg = str(getattr(e, 'reason', e))
        print(f"[CodeVault] Server unreachable: {error_msg}")
        
        if _CV_LEASE_ENABLED:
            valid, msg = _cv_validate_lease(license_key)
            if valid:
                print(f"[CodeVault] {msg}")
                return True
            else:
                _cv_show_error("OFFLINE - LICENSE REQUIRED",
                              "Cannot validate license offline.",
                              f"{msg}\n\nPlease connect to the internet.")
                return False
        else:
            _cv_show_error("CONNECTION REQUIRED",
                          "This application requires an internet connection.",
                          "Offline mode is not enabled for this build.")
            return False

# =============================================================================
# GLOBAL EXCEPTION HANDLER
# =============================================================================

def _cv_excepthook(exc_type, exc_value, exc_tb):
    """Global exception handler for user code crashes."""
    import traceback
    
    error_msg = f"Type: {exc_type.__name__}\nMessage: {exc_value}"
    details = traceback.format_exc()
    
    _cv_show_error("APPLICATION ERROR",
                  "An unexpected error occurred in the application.",
                  details,
                  is_fatal=True)

_cv_sys.excepthook = _cv_excepthook

# =============================================================================
# RUN VALIDATION
# =============================================================================

if not _cv_validate_license():
    _cv_sys.exit(1)

# ============ END CODEVAULT LICENSE PROTECTION ============
'''


def get_license_wrapper(
    license_key: str,
    server_url: str,
    lease_enabled: bool = True,
    public_key: str = "",
    binary_hash: str = "skip",
    heartbeat_interval: int = 300,
    app_name: str = "Protected Application",
    show_branding: bool = True,
    brand_name: str = "CodeVault",
    brand_url: str = "https://codevault.dev",
    brand_primary_color: str = "#6366f1",
) -> str:
    """
    Get the unified license wrapper code.

    Args:
        license_key: License key to embed (or "DEMO" or "GENERIC_BUILD")
        server_url: Server URL for license validation
        lease_enabled: Whether to enable offline lease (default: True)
        public_key: Ed25519 public key PEM for signature verification
        binary_hash: SHA-256 hash of binary for integrity checking (default: "skip")
        heartbeat_interval: Heartbeat interval in seconds (default: 300)
        app_name: Application name for UI (default: "Protected Application")
        show_branding: Show CodeVault branding (default: True for free tier)
        brand_name: Custom brand name (Business/Enterprise only)
        brand_url: Custom brand URL (Business/Enterprise only)
        brand_primary_color: Custom primary color hex (Business/Enterprise only)

    Returns:
        Complete wrapper code ready to be prepended to user code
    """
    code = UNIFIED_LICENSE_WRAPPER_TEMPLATE.replace("{license_key}", license_key)
    code = code.replace("{server_url}", server_url)
    code = code.replace("{lease_enabled}", "True" if lease_enabled else "False")
    code = code.replace("{public_key}", public_key if public_key else "")
    code = code.replace("{binary_hash}", binary_hash if binary_hash else "skip")
    code = code.replace("{heartbeat_interval}", str(heartbeat_interval))
    code = code.replace("{app_name}", app_name)
    code = code.replace("{show_branding}", "True" if show_branding else "False")
    code = code.replace("{brand_name}", brand_name if brand_name else "CodeVault")
    code = code.replace(
        "{brand_url}", brand_url if brand_url else "https://codevault.dev"
    )
    code = code.replace(
        "{brand_primary_color}",
        brand_primary_color if brand_primary_color else "#6366f1",
    )

    return code


# Keep backward compatibility
PYTHON_WRAPPER_TEMPLATE = UNIFIED_LICENSE_WRAPPER_TEMPLATE
